spring:
  application:
    name: gateway-service

  # Configuracion gateway
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**

        - id: match_route
          uri: http://localhost:8082
          predicates:
            - Path=/match/**

# Logging
logging:
  level:
    root: INFO

